### ISSUE TITLE
A question about   remove the "#"

### ISSUE THREAD

**Issue by telunmeiyoususu** [MaartenJongeneel/readyaml#1]
Dear,
        When i use the code, I find an issue about remove the "#".
        My yaml file  is this:

```
         Waveguide:
              layer: [1, 0]
              layer_in_name: true
              hatch_pattern: dotted
              width: 1
              color: "#ff9d9d"
          EleGround:
              layer: [10, 0]
              layer_in_name: true
              hatch_pattern:  dotted
              width: 1
              color: "gold"
```

 When use this code, I find that the key-value  is not correct of:
         `color: "#ff9d9d"`
        The reason is the begin of the value is "#", as the figure show:
![image](https://github.com/MaartenJongeneel/readyaml/assets/53967332/912eaf0b-f8f3-47f3-85cb-e3c8ac20f4b4)
![image](https://github.com/MaartenJongeneel/readyaml/assets/53967332/e6787be3-bfb9-43da-b59e-a3e41898136c)
        Please check my issue.
Thanks a lot!
